### ISSUE TITLE
Thymeleaf 3 support

### ISSUE THREAD

**Issue by yvanavermaet** [connect-group/thymeleaf-extras#1]
Hi

I was wondering if you are planning to support the new Thymeleaf 3?

Kind regards,
Yannick

**Comment by 4dz** [comment]
It will depend on demand and whether there is a 'hook' I can use in Thymeleaf 3.

Thymeleaf have added Decoupled Templates in v3 which is the same idea. It uses XML and XPath selectors instead of CSS3. 

Personally i think CSS3 is a better selector as frontend devs are familiar with it; so if I get some time I'd like to look Into it

**Comment by yvanavermaet** [comment]
Agreed. I'm personally not a big fan of decoupled templates, so the only other alternative I'd have, is to use th:block elements around a piece of text.

I prefer to use thymeleaf-extras ;-)

**Comment by 4dz** [comment]
Ah I got confused - thought yhis was Thyme sheet repo!

These attributes should be convertible. Will have to look into it!

**Comment by yvanavermaet** [comment]
Hi @4dz 

Did you have a chance to look at converting this for Thymeleaf 3?

Thanks in advance.

Kind regards,
Yannick

**Comment by yvanavermaet** [comment]
Hi @4dz 

Do you have any idea when you might get to this?
If you don't have time for this, feel free to let me know. That way I can ask one of my colleagues to rebuild the necessary parts of this module.

Thanks.

Kind regards,
Yannick

**Comment by 4dz** [comment]
Hi,

I did spend some time looking at it. It's built using TDD, and unfortunately Thymeleaf3 doesn't support that. So I spent time looking into how to retrofit that into Thymeleaf3.

If I wasn't stubborn about TDD I think it would be quite trivial to convert the code over, and I would like to do it - but realistically not for at least a couple of weeks.

Apologies if that isn't very helpful - unfortunately other commitments mean I won't be able to do it til then!

Do let me know if you do convert it yourself and how you get on.

**Comment by jegoossens** [comment]
Hi @4dz ,

I'm working on porting this to thymeleaf 3, which should be finished soon. 
I have one question though, what is the difference between utext-before and insert-utext-before. 
Imho they are functionally the same, where insert-utext-before actually is just a utext-before which replaces an empty text. If these assumptions are correct, they would have the same technical implementation in TH 3.

**Comment by jegoossens** [comment]
Hi @4dz ,
Can you check out my pull request?

**Comment by 4dz** [comment]
Apologies for the delay, but have reviewed and am in the process of publishing...

**Comment by yvanavermaet** [comment]
Seems this is ok, but the issue remained open. Closing it now. Thanks a lot @jegoossens & @4dz
